server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: uniAttend
  datasource:
    url: jdbc:postgresql://dpg-d11i52nfte5s73980fkg-a:5432/uniattend
    username: uniattend
    password: qWaGEoR4iIHt2Vam4A0VB7h7RzofEQrG
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    salt-rounds: 12


# ???? ?????????????
userRoles:
  admin: admin
  user: user
  teacher: teacher
  student: student

api:
  path:
    admin: /api/v1/admin
    user: /api/v1/user
    teacher: /api/v1/teacher
    student: /api/v1/student